# Generated by Django 5.1.2 on 2024-10-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('transaction_type', models.CharField()),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField()),
            ],
        ),migrations.RunSQL(
            """
                CREATE MATERIALIZED VIEW transactions_mv AS 
                SELECT 
                    client_id,
                    currency,
                    SUM(CASE WHEN transaction_type = 'buy' THEN amount ELSE 0 END) AS total_spent,
                    SUM(CASE WHEN transaction_type = 'sell' THEN amount ELSE 0 END) AS total_gained
                FROM transactions_transaction
                GROUP BY client_id, currency
            """,
            """
                DROP MATERIALIZED VIEW transactions_mv;
            """)
    ]
