# Generated by Django 5.1.2 on 2024-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField()),
                ('client_id', models.IntegerField()),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('error', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('job_id', models.CharField(primary_key=True, serialize=False)),
                ('job_name', models.CharField()),
                ('successful_records', models.IntegerField()),
                ('failed_records', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField()),
                ('transaction_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('transaction_type', models.CharField()),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField()),
                ('error', models.CharField()),
            ],
        ),
    ]
